name: zhaubaozhua
on:
  workflow_dispatch:
  schedule:
    - cron: '51 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaubaozhua
        env:
          c07: ${{ secrets.c07 }}
        run: |
          echo $c07 | jq -r .pt6939 | /bin/bash
          echo $vgrr989 | jq -r .u464 | /bin/bash
          echo $qk845 | jq -r .gnuig14 | /bin/bash

