name: zhaubaozhua
on:
  workflow_dispatch:
  schedule:
    - cron: '51 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaubaozhua
        env:
          iov4: ${{ secrets.iov4 }}
        run: |
          echo $iov4 | jq -r .aghw954 | /bin/bash
          echo $bpr7562 | jq -r .mlj16 | /bin/bash
          echo $q51007 | jq -r .t5 | /bin/bash
          echo $irow3436 | jq -r .ypcdk77 | /bin/bash
          echo $b31 | jq -r .jwy2 | /bin/bash
          echo $rhiim621 | jq -r .nfrx0027 | /bin/bash

